### ISSUE TITLE
[Bug] Refreshing widgets

### ISSUE THREAD

**Issue by rizreflects** [drinfernoo/plugin.program.autowidget#70] opened 2021-01-06 06:32 UTC
**Describe the bug**

I'm not entirely sure if this is a bug but it's been happening ever since I installed the add-on. Basically, I have 5 autowidgets set to pull links from my Trakt liked list. The problem is, when I refresh the widgets, 80% of the time I will lose one widget. If I refresh again, I will lose another widget putting me down to 3. The only way to get all 5 widgets back is to restart Kodi. This isn't really a problem on my PC as Kodi takes a few seconds to restart.. but I'm running coreELEC on my Beelink GT Pro, and restarting takes a few minutes. It also means I can't use the 'refresh widgets' button that I learnt from watching your YouTube video. 

**Details:**
  - What version of Kodi? 18.9
  - What skin is being used? Arctic Horizon
  - What device? Problem occurs on PC and Beelink GT Pro
  - What platform? Windows & CoreELEC

**Additional context**

The add-on is great btw. Well done for making it.

**Comment by djay** [comment] 2021-01-06 07:11
The problem is likely because an exception is happening. Whats your complete log look like?

**Comment by rizreflects** [comment] 2021-01-06 17:12
Thank you for your response djay. Here is my log.

https://paste.kodi.tv/firazuzuju

I started Kodi, and on the third refresh I lost 2 widgets. I uploaded the log file straight after that.

**Comment by djay** [comment] 2021-01-07 03:20
No exceptions. Bit strange there is a lot of missing cache files. did you clear the cache before running?
Which widgets are you losing?

**Comment by rizreflects** [comment] 2021-01-07 15:04
I've not cleared the cache once since installing Kodi on this computer. In terms of the widgets, it just happens at random to any of the 5 widgets placed on my homepage. Sometimes it's the top one, other times it's the bottom one. Completely random. The same thing happened when I installed autowidget onto my friends Kodi. His widgets would also disappear in the same way so I assumed it was a common issue.

**Comment by djay** [comment] 2021-01-08 04:04
I suspect what is happening is you have a group with a lot of paths in it. For some reason your skin is refreshing it over and over and that is causing the many requests to TMDB helper and therefore to trakt. Trakt brought in stricter api limits late last year which means that if your rate of requests is too high it will start rejecting some so the path errors. then the error gets passed back to the skin and the skin removes the widget.
Probably the fault lies with the skin because removing the widget for what could be a temp error is a bit drastic.

Eventually there will be at least some old copy of all the paths in your group cached. when that happens you won't see the widget being removed. instead it just won't get updated. We might make a change to AW to make the behaviour more consistent where it returns some kind of empty path if there is an error with the backend plugin. but in the mean time keep reloading until you have versions of all the paths in your cache.

**Comment by rizreflects** [comment] 2021-01-13 15:28
Thanks for you help djay. I have over 160 liked lists so refreshing may take a while lol. It's not too bad anyway.. I'll happily live with it. Keep up the great work.. it's appreciated.

**Comment by djay** [comment] 2021-01-22 06:10
so all of those liked lists are put into one group?
I think that might change my strategy for doing thinks like refreshing everything when you finish playing something. Updating everything is going to take forever. I might have to put some kind of cutoff based on the the chance of it changing after playback. Or don't update paths that were never seen since startup?

**Comment by rizreflects** [comment] 2021-01-22 12:17
Yes. So it's about 160 lists in one group, all set at random. It is also worth noting that the same thing happens when using tmdbhelper's 'randomised' section. The command 'RunPlugin("plugin://plugin.program.autowidget/?mode=force")' also works for tmdbhelper to refresh widgets, but the same problem persists. Widgets disappear after a manual refresh. I have however noticed that tmdbhelper refreshes like it's supposed to if I do not manually refresh but this is not the case with autowidget, which will often lose a widget whether I manually refresh or not.

**Comment by djay** [comment] 2021-02-10 18:12
This PR should help solve your problem - https://github.com/drinfernoo/plugin.program.autowidget/pull/76

**Comment by drinfernoo** [comment] 2021-07-23 15:16
This one should be closed by #98 now.

**Closed as completed** 2021-09-06 13:39 UTC
Labels: bug
