### ISSUE TITLE
[Bug] Python Errors, Active-Widgets Menu not accessible.

### ISSUE THREAD

**Issue by Ramalama2** [drinfernoo/plugin.program.autowidget#72] opened 2021-01-15 23:02 UTC
Hi Guys xD
FYI: I grab with autowidget from: xStream, Amazon Vod, Netflix, Filmix, WRP-Metaplayer
What i grab: From them all categories that i combine, like: New Movies, Popular Movies, New Series, Sci-Fi, Blockbuster, etc...
And im using the AuraMod Skin to show all the widgets. I'm using only the "Merging" View for all widgets!
Autowidget should refresh every 2h...

Now the Bug:

**Describe the bug**
Not possible to enter "Active-Widgets" Menu. (Throws an error)
The widgets itself still works.

**Details:**
  - 18.9
  - AuraMod
  - Shield TV 2019
  - Android 9

**LOGS:**
`2021-01-15 23:29:30.420 T:17123   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument of type 'bool' is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/main.py", line 13, in <module>
                                                router.dispatch(_plugin, _handle, _params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/common/router.py", line 71, in dispatch
                                                is_dir, category = menu.merged_path(group, widget_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/menu.py", line 455, in merged_path
                                                titles=titles, num=len(paths), merged=True)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/menu.py", line 235, in show_path
                                                files = refresh.get_files_list(path, titles, widget_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/refresh.py", line 264, in get_files_list
                                                filtered_files = [x for x in files if x['title'] not in titles]
                                            TypeError: argument of type 'bool' is not iterable
                                            -->End of Python script error report<--
2021-01-15 23:29:30.658 T:17082   ERROR: GetDirectory - Error getting plugin://plugin.program.autowidget/?action=merged&group=neue_filme-1610399057.92&mode=path&id=e54223fb-e756-458f-921c-1a143660fa66&refresh=&reload=`

**FULL Log:**
https://cloud.golima.de/s/G5epSXJ4SG8t3pj
[kodi.log](https://github.com/drinfernoo/plugin.program.autowidget/files/5823301/kodi.log)

Thank you :-)

**Comment by drinfernoo** [comment] 2021-01-16 19:01
Can you test 0.0.1113 from the devrepo? I may have fixed it there.

**Comment by Ramalama2** [comment] 2021-01-16 20:05
Thanks for the fast reply.
One one shield, i have simply deleted *.cache, *.history, *.widged files and linked again in the skin 😂
That fixed the issue.

On the other shield (all same, like a clone), i tryed 0.1113 (the active widgets menu still throws error) 🙈
I guess, i will simply do the same as on shield1 and im good 😂
But i will wait for your okay, if you want to test something, here is the log:
https://cloud.golima.de/s/QH4eMdaoKP5yXq2
(Check at the very end after 20:58:xx) (tryed to open active widgets in the plugin)


Something unrelated to this bug:
- On the initial linking in the skin, autowidget popup a window, where you can select the sources and you click okay (merging view for example)
- is it possible to add an option into the settings, to simply:
"Select sources as default for new widget: All/Popup"
All stays for simply select always all sources & Popup for the actual behavior 🙈

Would make it possible for me, that i can simply delete all the cache/history/widget files... And if the skin tryes to access autowidget, you don't get asked 500 times 🙈

**Comment by drinfernoo** [comment] 2021-01-16 22:27
Are you saying that when Kodi loads, it asks you to choose your merged paths again... every time? For every widget?

Because that would be a bug that deserves its own issue.

I do like the idea of an "All/Popup", but currently the design is such that if there are less than five paths in a group, they will all be selected. I'd prefer to keep this type of logic... potentially with the option to change *that* threshold instead.

If you'd like me to pursue that, please open it as a separate issue as well, or I'll forget 😅

Give me some time and I'll check out what's still happening in this issue.

**Comment by Ramalama2** [comment] 2021-01-17 10:58
> Are you saying that when Kodi loads, it asks you to choose your merged paths again... every time? For every widget?
> 
> Because that would be a bug that deserves its own issue.
> 
> I do like the idea of an "All/Popup", but currently the design is such that if there are less than five paths in a group, they will all be selected. I'd prefer to keep this type of logic... potentially with the option to change _that_ threshold instead.
> 
> If you'd like me to pursue that, please open it as a separate issue as well, or I'll forget 😅
> 
> Give me some time and I'll check out what's still happening in this issue.

I open then a separate "request/bug" for that.
It does ask me every time, if i delete the *.widget/*.history/*.cache files inside the userdata autowidgets plugins folder.
Only one group has 5 sources, all other groups have less as 5. It even asks me, if there is only one source 😂

Very rarely, it opens a window to select sources, if i start kodi and didn't deleted anything...
What i think is, that probably i turned off kodi, while Autowidgets was refreshing the sources 🙈

However, will open a separate thing for that 🙈
Thanks 👍

**Comment by Ramalama2** [comment] 2021-01-17 13:23
I found out what exactly cause the error.

If i make a group that is called "Zuletzt Hinzugefügt"
---> ü

And load it in the skin to make it "active", it will break the addon.
Then you can't enter active widgets anymore etc...


I have deleted "Zuletzt Hinzugefügt" in My Groups, made a "Zuletzt Hinzugefuegt" Group and "Active Widgets" works instantly again.

So we have a workaround at least, don't use ü/ä/ö/ß in group names 😘

**Comment by drinfernoo** [comment] 2021-01-17 14:12
Yeah, the issue is with Unicode characters, and it seems I'm always missing *somewhere* in the code to handle them properly. I'll get it eventually 😅

**Comment by Ramalama2** [comment] 2021-01-17 20:22
Just make a stupid wiki entry, to not use special characters, like ü/ä/ü/ß/ëé, or only use normal characters like a-z,A-Z,0-9, etc... For group names 😂

Who the hell needs it, we can name the widgets in the skin with all the special characters 😂

Soon as you will need to rewrite the scripts for python 3, it will probably gets fixed by itself 😂

**Closed as completed** 2021-01-18 19:17 UTC
Labels: bug
