### ISSUE TITLE
Unable to create widgets[Bug]

### ISSUE THREAD

**Issue by Tonkapug** [drinfernoo/plugin.program.autowidget#100] opened 2021-07-25 09:43 UTC
**Describe the bug**
When creating a widget group and configuring it to Cycle an error is produced. Upon further inspection, there is no active widget created.

**To Reproduce**
1.  Create a widget group with two or more items
2.  Activate the widget with the static, cycling, or merged action.
4.  The result is an 'Error showing' message

**Expected behavior**
To create a cycling, next path widget 

**Screenshots**
![Error Screenshot](https://user-images.githubusercontent.com/6201305/126894655-31c03fb8-ee20-4ef1-af97-2459cff667ff.jpg)

**Details:**
  - What version of Kodi? - Kodi 19.1 Windows
  - What skin is being used? - Stock Estuary, Xonfluence, Estuary Mod or any other skin
  - What device? - Desktop PC
  - What platform? - Windows 10

**Additional context**
I can't tell you how long this issue has been present as I have only recently used Autowidget for shortcuts. However, in the past, I have used widgets and they worked fine. I know there have been recent updates of the add-on pushed so maybe something got messed up. Kodi.log attached

[kodi.log](https://github.com/drinfernoo/plugin.program.autowidget/files/6873631/kodi.log)

**Comment by drinfernoo** [comment] 2021-07-25 11:48
Are you not choosing any paths when you make the widget?

**Comment by Tonkapug** [comment] 2021-07-25 12:41
> Are you not choosing any paths when you make the widget?

Yes, I am choosing paths. Sorry, I didn't mention that. I've tried both leaving the options green and selecting which changes them white. Neither creates the widget. When I select both items which changes them both white I get the error.  Both choices should be in the log. 

Autowidget Version 3.3.6

**Comment by drinfernoo** [comment] 2021-07-25 12:57
They're selected (green, in your case) by default. If you choose no paths (deselect all), there is nothing to show. I should look into making sure there is no error here, but are you saying that even if you leave them selected, the widget still doesn't work?

**Comment by drinfernoo** [comment] 2021-07-25 13:00
I'm also a bit suspicious of this line:
`2021-07-25 07:04:57.257 T:21820    INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: plugin.video.themoviedb.helper v99.3.24 installed`

Where did you get this version of TMDbHelper?

**Comment by Tonkapug** [comment] 2021-07-25 13:03
That is correct...even building the widget with both items highlighted in green the widget is not created. It appears to complete and the list of titles show up but when I go to active widgets there are none. I go to addon_data and no 'Widget' file is created there either. Only the 'Group' file is there.

**Comment by Tonkapug** [comment] 2021-07-25 13:30
> I'm also a bit suspicious of this line:
> `2021-07-25 07:04:57.257 T:21820 INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: plugin.video.themoviedb.helper v99.3.24 installed`
> 
> Where did you get this version of TMDbHelper?

I just tested and that is not the issue. I can resend the log with the latest TMDBHelper version if needed. The only difference in that version is the artwork. I edited it myself as I do not like the included artwork.

**Comment by Tonkapug** [comment] 2021-07-25 13:33
New Log

[kodi.log](https://github.com/drinfernoo/plugin.program.autowidget/files/6873959/kodi.log)

Everything runs fine (as in no error) when leaving highlighted 'Green' but there are no active widgets and no 'Widget' file is created.

**Comment by drinfernoo** [comment] 2021-07-25 15:00
It doesn't appear you are actually creating a widget... You only have Estuary and Estouchy installed (by default, I might add), so you can't define your own widgets in the first place.

A `.widget` file is only created whenever a widget is created on the skin, and thus populates "Active Widgets" with widgets which are... active 😅

**Comment by Tonkapug** [comment] 2021-07-25 15:43
> It doesn't appear you are actually creating a widget... You only have Estuary and Estouchy installed (by default, I might add), so you can't define your own widgets in the first place.
> 
> A `.widget` file is only created whenever a widget is created on the skin, and thus populates "Active Widgets" with widgets which are... active 😅

lol...you're correct. It works fine on Estuary Mod but It appears this is not doable on the Xonfluence skin. I will have a closer look when i get a chance...Sorry for wasting your time lol.

**Comment by Tonkapug** [comment] 2021-07-25 16:03
@drinfernoo I got it working on Xonfluence. Had to create the widget in Estuary Mod and use that shortcut as a widget in Xonfluence and the widget file was then created. You can mark this as closed.

**Comment by Tonkapug** [comment] 2021-07-25 17:40
@drinfernoo That didn't work....the widget has to be rebuilt on each reboot. Anyway for these to work with Xonfluence? I've been reading your post on the kodi forum and i see you mention it should work with Xonfluence. Link below

https://forum.kodi.tv/showthread.php?tid=352934&pid=2937574#pid2937574

**Comment by drinfernoo** [comment] 2021-07-25 17:45
I'll have to test again, but they should work fine... they did in Leia, but there is a new maintainer for Xonfluence from what I understand, so maybe he's changed something that's broken compatibility.

**Comment by Tonkapug** [comment] 2021-07-25 17:54
Thanks for the assistance. I can create a favorite only for the 'Cycling' path and that always produces a popup window to choose Random or Next. The widget works fine but on every reboot, you have to rebuild it, and also if you open Autowidget and choose 'Active widgets' the widget file is immediately deleted.

**Comment by drinfernoo** [comment] 2021-07-25 18:03
I'll load up the new Xonfluence tonight and see what I find.

**Comment by Tonkapug** [comment] 2021-07-25 18:26
> I'll load up the new Xonfluence tonight and see what I find.

I appreciate it, bud. I know there is a version with skinshortcuts out there but i'd prefer without. I have the Matrix version., link below.

https://github.com/bartolomesoriano/skin.xonfluence

**Comment by drinfernoo** [comment] 2021-07-25 21:16
So the issue is that AutoWidget tries to "clean out" unused `.widget` files on startup, and Xonfluence reads widget paths from `favourites.xml`, which I wasn't scanning to see if a widget was "in use". I've just pushed a fix which is live on the devrepo in version 0.0.1405, and will get merged to stable at some point in the near future.

The side effect of this particular fix is that if you intend on **not** using a widget anymore, you'll need to either remove it from your Favorites or remove it from the "Active Widgets" menu, or it will be kept forever (as AutoWidget can't remove it from the `favourites.xml` file directly), continue to show up in the "Active Widgets" menu, and be refreshed every cycle *even if you're not using it anymore*.

**Comment by Tonkapug** [comment] 2021-07-25 22:46
I will give this a test in the morning. Xonfluence should read the widget path from settings.xml and not favorites.xml. I wouldn't want to leave these in my favorites. I appreciate you looking into this for me and i will get back to you with the results.

**Comment by drinfernoo** [comment] 2021-07-26 00:04
Actually you're right, it does... I still think that's what was happening to you, in any case. Give the test release a shot and see. I'd recommend specifically testing version 0.0.1405, as I made a couple other changes since then that may or.may not affect your experience.

**Comment by Tonkapug** [comment] 2021-07-26 11:09
So, I tested this and found the actual widget is created but produces the error code as I mentioned in my first post. 

kodi.log error

`2021-07-26 08:37:16.133 T:1336     INFO <general>: plugin.program.autowidget: [ action: cycling ][ group: trending-1627296664.568058 ][ id: 81d7a4dc-8e4d-4437-af6e-486118a540d4 ][ mode: path ][ refresh: $INFO[Window(10000).Property(autowidget-81d7a4dc-8e4d-4437-af6e-486118a540d4-refresh)] ]
2021-07-26 08:37:18.921 T:1336    ERROR <general>: plugin.program.autowidget: Traceback (most recent call last):
                                                     File "C:\Users\DESKTOP\AppData\Roaming\Kodi\addons\plugin.program.autowidget\resources\lib\common\router.py", line 75, in dispatch
                                                       is_dir, category, is_type = menu.path_menu(group, action, widget_id)
                                                     File "C:\Users\DESKTOP\AppData\Roaming\Kodi\addons\plugin.program.autowidget\resources\lib\menu.py", line 545, in path_menu
                                                       titles, cat, type = show_path(group_id, _label, widget_id, widget_path)
                                                     File "C:\Users\DESKTOP\AppData\Roaming\Kodi\addons\plugin.program.autowidget\resources\lib\menu.py", line 313, in show_path
                                                       files, hash = refresh.get_files_list(path, path_label, widget_id)
                                                   TypeError: get_files_list() takes from 1 to 2 positional arguments but 3 were given`

The error is then the only poster viewable on the skin's home page widget. It appears it will only stay there if the favorites are kept, as well. If I remove the favorite it's right back to creating the widget on each boot.  That's because the skin reads the settings.xml which only has a link to the 'Cyclying' menu item in the Autowidget widget group as does the favorites. It would be better to scan the settings.xml rather than favorites.xml. That way the favorite can be deleted.

I'm not sure why the widget isn't created, correctly. Yesterday it was fine, the only issue was it just would not stick on reboot because the skin keeps reading settings.xml which only has a shortcut for the 'Cycling' action. 

favorites.xml

`<favourite name="Trending (Cycling)" thumb="special://home/addons\plugin.program.autowidget\resources\media\icon\shuffle.png">ActivateWindow(10025,&quot;plugin://plugin.program.autowidget/?action=cycling&amp;group=trending-1627296664.568058&amp;id=fbfd508f-a290-4c6d-99ee-6cf7616a55f6&amp;mode=path&amp;refresh=%24INFO%5bWindow(10000).Property(autowidget-fbfd508f-a290-4c6d-99ee-6cf7616a55f6-refresh)%5d&amp;reload&quot;,return)</favourite>`

Settings.xml

`<setting id="HomeItem.3.Widget" type="string">plugin://plugin.program.autowidget/?action=cycling&amp;group=trending-1627296664.568058&amp;id=fbfd508f-a290-4c6d-99ee-6cf7616a55f6&amp;mode=path&amp;refresh=%24INFO%5bWindow(10000).Property(autowidget-fbfd508f-a290-4c6d-99ee-6cf7616a55f6-refresh)%5d&amp;reload</setting>`

**Comment by drinfernoo** [comment] 2021-07-26 11:57
I know I said to try 0.0.1405, but could you try the latest devrepo release instead? I fixed the bug you're seeing now already.

**Comment by Tonkapug** [comment] 2021-07-26 12:21
It;'s working now! However, it will only function if the favorite is kept. If the favorite is removed you have to re-create the widget on each boot. Any way to eliminate having to keep the favorite?

**Comment by drinfernoo** [comment] 2021-07-26 12:37
Actually... I found the bug causing that as well 🤦 I actually *wasn't* scanning the skin settings files, due to a goof in my path construction. I think with that in mind, I'm going to *remove* scanning of the `favourites.xml`, and it should still work just fine.

Give 0.0.1415 a try.

**Comment by Tonkapug** [comment] 2021-07-26 12:51
You got it! Widget is created and works fine on reboot even with favorite deleted. I appreciate you looking into this. Will this be added to master?

**Comment by drinfernoo** [comment] 2021-07-26 13:05
Yeah, ill probably do a stable release later today.

**Closed as completed** 2021-07-26 23:40 UTC
Labels: bug, upcoming

**Comment by Tonkapug** [comment] 2021-08-24 19:35
@drinfernoo How would I go about sorting that widget in an XML different than settings.xml?  I'm using a different skin and the widget shortcut is now located in Includes_Home.xml.

I tried manipulating your code to get it working but to no avail. Obviously, I'm nowhere near correct lol. The widget works fine but has to be activated after each reboot as in the Xonfluence skin. 

Here's what i edited in manage.py
_widget = utils.translate_path("special://addons/skin.estuary.matrix.pkscout.mod/xml/")

    addons = utils.call_jsonrpc(params)
    if "error" not in addons:
        for addon in addons["result"]["addons"]:
            path = os.path.join(
                _widget, "Includes_Home.xml"

**Comment by drinfernoo** [comment] 2021-08-24 20:43
I don't think that particular file you're looking at will be the one... Skin files are rarely (if ever) modified directly when widgets come into play.

The only file I know of that works this way is the `script-skinshortcuts-includes.xml` file, which is actually generated **by** Skin Shortcuts so that the skin can use those widgets.

It's possible that we could scan that file, but this may have unexpected behavior during widget cleaning.

I'll see if I can test out the skin you're using to see if I can figure out what's going on there.

**Comment by Tonkapug** [comment] 2021-08-24 21:02
This skin doesn't have the ability to create widgets outside of the video library. It's basically the stock Estuary skin with a few simple modifications. However,  I have modified one of the skin files to allow a widget on the home screen. The widget does work fine but I just have to reenable it after each boot.  If needed, I can show you how I went about this.  It was a quick edit to add the widget path.

**Comment by Tonkapug** [comment] 2021-08-24 21:20
I made a mistake in my previous post. The name of the file is 'Includes_Mod.xml, not "Includes_Home.xml".

**Comment by drinfernoo** [comment] 2021-08-24 21:41
I won't be supporting that type of thing. You *may* be able to make an edit in AutoWidget to have it work, but it would be a bit more complicated than a single line change, and would get overwritten with each AutoWidget update...

It would be better to ask the developer to implement widgets into their skin, at this point.

**Comment by Tonkapug** [comment] 2021-08-24 21:46
Thanks...I was hoping it was a simple fix but should have known it would be a bit more complicated. I wasn't expecting you to support it in your add-on. I was more looking for help on getting it working. I would have just re-added the mod each time an update was pushed.
