### ISSUE TITLE
Autowidget no longer works for me

### ISSUE THREAD

**Issue by rizreflects** [drinfernoo/plugin.program.autowidget#107] opened 2021-09-07 19:49 UTC
After the last update autowidgets not working at all on my shield. All 7 of my autowidgets look like this:

![IMG_20210907_204253.jpg](https://user-images.githubusercontent.com/76912707/132402418-9d5cd159-4dd4-4f2b-8bef-eee5c54fa4fa.jpg)

Although it says loading content, it doesn't actually load. 

Also when starting Kodi I get an autowidget error message every time.. here's the log for that:

https://paste.kodi.tv/epuhiterot

Any help will be appreciated as I'm not sure how to fix this issue...

**Comment by drinfernoo** [comment] 2021-09-07 19:50
Can you clear cache from settings and check that it works afterwards?

**Comment by rizreflects** [comment] 2021-09-07 19:51
I done that.. also refreshed the widgets afterwards.. no success.

**Comment by drinfernoo** [comment] 2021-09-07 19:56
Can you attach an AutoWidget backup?

**Comment by rizreflects** [comment] 2021-09-07 20:10
Backup? Can you tell me how to do this?

**Comment by drinfernoo** [comment] 2021-09-07 21:37
@rizreflects There's an option in settings 😉

**Comment by rizreflects** [comment] 2021-09-08 00:20
https://1drv.ms/u/s!AgpGD5FbtkrWgP4wpL7AE0_3ERwm4w

**Comment by antoniopetreski** [comment] 2021-09-08 08:33
This is happening to me as well.. after the update.

Whenever there's AutoWidget error popup, it's the same thing in the logs.
```
Error type: exceptions.AttributeError
Error contents: 'NoneType' object has no attribute 'get'
```

Also, it says 
"Could not read JSON from ./addon_data/plugin.program.autowidget/..." and "No JSON object could be decoded" and i haven't touched anything in the userdata folder since i installed kodi.

Hope you'll find this information helpful 🙂

**Comment by drinfernoo** [comment] 2021-09-08 13:40
@rizreflects I'm unable to reproduce this. The "Loading Content..." tile does appear (as well as the "Updating Widgets" notification... while content is being loaded. Once they're loaded, the notification goes away, and I can see the widgets.

I tested this by loading your widgets into my skin, and can see them just fine.

@antoniopetreski That sounds like a different issue, but I'd need a full log to diagnose further.

**Comment by rizreflects** [comment] 2021-09-08 14:14
> @rizreflects I'm unable to reproduce this. The "Loading Content..." tile does appear (as well as the "Updating Widgets" notification... while content is being loaded. Once they're loaded, the notification goes away, and I can see the widgets.
> 
> I tested this by loading your widgets into my skin, and can see them just fine.
> 
> @antoniopetreski That sounds like a different issue, but I'd need a full log to diagnose further.

Can you clear the cache and refresh the widgets... Do they still load up for you?

**Comment by drinfernoo** [comment] 2021-09-08 16:25
@rizreflects It is working for me after clearing cache as well, but can you try 0.0.1458? I've added some logic to remove more files during the cache clear, which may help.

**Comment by rizreflects** [comment] 2021-09-08 17:32
> @rizreflects It is working for me after clearing cache as well, but can you try 0.0.1458? I've added some logic to remove more files during the cache clear, which may help.

Just tested 0.0.1458.. seems to be working. I'd appreciate it if you could push an update to the stable repo sooner rather than later.. I have autowidget installed on a few of my friends devices aswell and they wouldn't know what I'm talking about if I told them to install from the dev repo. 

Thanks a lot.

**Comment by rizreflects** [comment] 2021-09-08 17:45
Update: I just reverted back to the stable build from the dev one and everything seems to be working properly now. Widgets are refreshing and updating as intended. Not sure why that problem occured but it's sorted now so I'm gonna close this issue to not take up anymore of your time.

**Comment by antoniopetreski** [comment] 2021-09-08 22:53
@drinfernoo it's still not fixed on my end, it might be a different issue, however I'll post a comment instead of opening a new issue.

It just says "Loading content..." at the top and the reload/refresh item at the bottom. And whenever i press on the reload icon, the screen flicks few times, like it's making few attempts, but in the end the reloading/refreshing always fails
It's only happening on my Trakt widgets (with Seren/TheMovieDB). But if i enter the widgets manually through the AutoWidget addon, the content is displayed, the widget is properly set up.

Here's a log file
https://paste.kodi.tv/gekuzepeya

Note that i only updated the addon, i literally didn't do anything else.

**Comment by drinfernoo** [comment] 2021-09-09 02:52
@antoniopetreski Entering the widgets through AutoWidget opens it directly in the source, so that is not an indicator of the widget working properly, unfortunately.

This is a separate issue, which will have to be looked at, as I haven't seen that particular error crop up at all. If you'd open a new issue (you can even just copy/paste the comment you made) that would help me not lose it, since this one is already closed.

In the meantime, can you try deleting any of the `.cache`, `.history`, and `.queue` files in `special://userdata/addon_data/plugin.progran.autowidget`, and see if that helps?

**Comment by rizreflects** [comment] 2021-09-09 15:11
@drinfernoo could you possibly add an option to hide the 'updating widgets' notification?

Also I've noticed that when manually refreshing the widgets via AW settings, Kodi (on the shield) sometimes crashes.

I've also noticed widgets take considerably longer to refresh. Just out of curiousity, is this because the cache is being cleared each time? Previously it wud take 20- 30 seconds for all 7 of my autowidgets to refresh, whereas now it tends to take over a minute or two.

**Comment by drinfernoo** [comment] 2021-09-09 15:16
> @drinfernoo could you possibly add an option to hide the 'updating widgets' notification?

Possible, but it is meant to be an indicator that things are working correctly.

> Also I've noticed that when manually refreshing the widgets via AW settings, Kodi (on the shield) sometimes crashes.

If you refresh every widget, that is going to be a load on the system, no matter which system you're using.

> I've also noticed widgets take considerably longer to refresh. Just out of curiousity, is this because the cache is being cleared each time? Previously it wud take 20- 30 seconds for all 7 of my autowidgets to refresh, whereas now it tends to take over a minute or two.

The cache isn't cleared each time. I don't really have any way of knowing why they're refreshing slowly, but if there are paths trying to show which are not cached yet, then they have to be cached before they can be shown.

**Comment by rizreflects** [comment] 2021-09-09 15:40
For me, it's already simple enough to know if things are working properly. If the widgets are changing regularly and updating with new movies, it's a good indication that things are working well. Either way though, do what you feel is best. Thanks for all your work.

**Comment by rizreflects** [comment] 2021-09-09 18:48
Sorry to bother you again but I've noticed another problem.  It seems every 10-15 minutes the 'updating widgets' notification returns. I've set autowidget to refresh every hour and a half in settings so it's not because of that. Once it's finished updating, it doesn't refresh the lists, but rather the items inside the lists. Since most of my items are set to random via trakt, this update causes them to randomise every 10-15 minutes. I understand that the items will randomise because it's set that way in trakt, but previous versions of autowidget would only randomise it once when it initially loaded. There were no refreshes 10-15 minutes later. I thought I'd bring this to your attention as it may have been overlooked and definitely causes problems which weren't present before.

**Comment by drinfernoo** [comment] 2021-09-09 19:02
@rizreflects This is intended behavior, as the cache gets updated regularly now, where it was broken (and didn't) before.

**Comment by rizreflects** [comment] 2021-09-09 19:53
:/ surely that's gotta be a problem though right? Because it means you can't add any lists that are set to random (via trakt) to autowidget. I remember in the past when the cache would function properly, this problem was never there. I would have definitely noticed if it was.

Would you consider adding an option to update the cache once a week rather than every few minutes? I get why some lists would need to update often (lists like trending), but for sub-genres like the backup file I sent you once a week would be more than enough. This would solve the constant refreshing problem aswell. If I'm honest, it's just not usable for me in this state which is a shame because it's one hell of an add-on that I've used for years now. 

Of course, one option is to set my lists to anything other than random via trakt, but this is far from ideal. Setting the lists to random is the only way to ensure you see all the movies, as movies at the end of lists can easily be missed when dealing with lists that contain more than 2-300 movies. 

I really hope you'll look into this but ultimately it's your add-on. I'm just happy to help. Thanks a lot.

**Comment by rizreflects** [comment] 2021-09-09 19:57
(sorry if I used the term cache wrong) I'm just referring to the refreshing that occurs every 10-15 minutes.

**Comment by drinfernoo** [comment] 2021-09-09 21:49
@rizreflects I don't understand the complaint...

You sort your lists randomly, so that you'll see more content, but you're saying that AutoWidget changes the content *too often*?

**Comment by rizreflects** [comment] 2021-09-09 22:48
I think I'm doing a bad job at explaining.. let me start again. 

Let's say for example I like this list from seren, then add it to autowidget:

https://trakt.tv/users/rizreflects/lists/feel-good?sort=random,asc

Since this list is sorted as random through trakt, it randomises each time it is loaded on Kodi (as would be expected). The problem however, is each time you see the 'updating widgets' notification, autowidget triggers a refresh. So what happens is the movies in the list get randomised again. In other words, the order of the movies get changed, even as your browsing through them.

You can test it out and see for yourself by adding my list to autowidget and then observing the widget for 30 minutes. It will refresh 2-3 times, randomising the movies every time. 

Am I making any sense? If not I'll try and record a video so you know exactly what I mean. Basically, the problem that I have is the widgets refresh every 10-15 minutes, and in doing so changes the arrangement of movies within the list so long as it is sorted at random (through trakts side not Kodi). The items order will randomise even as you're scrolling through them.

**Comment by rizreflects** [comment] 2021-09-09 23:09
Here's a video of the problem 

https://streamable.com/dbhaj4

See how after the 'updating widgets' notification finishes the widget randomises? This occurs every time, which is every 10-15 minutes.

**Comment by drinfernoo** [comment] 2021-09-10 00:32
Again, this is expected behavior. We are getting the most up-to-date information about the list, so the order matches what is found in the add-on.

This is the same behavior that would be seen if you pointed a widget directly at an add-on and the widget was reloaded under normal circumstances... which can be at any time, and is typically controlled by a variety of factors, from the skin to the add-on, or other running services.

We are currently looking into the best solution for determining which widgets should be allowed to hold their cache for longer periods, but the widget "reload" will still happen, as it's the main mechanism that makes AutoWidget (or any widget) *able* to change their content without a skin reload.

**Comment by rizreflects** [comment] 2021-09-10 01:36
Alright no worries. I'll revert back to the previous version and manually clear the cache from now on. With 7 autowidgets all set to random it's just not usable for me anymore with the constant refreshes. Thanks for all your help though, appreciate it.

**Comment by drinfernoo** [comment] 2021-09-10 03:29
@rizreflects Bear in mind that this was always the way it should've been working (and did before 3.0.0). The reason it worked the way you liked was because the caching mechanism was broken.

**Comment by antoniopetreski** [comment] 2021-09-10 09:40
> In the meantime, can you try deleting any of the `.cache`, `.history`, and `.queue` files in `special://userdata/addon_data/plugin.progran.autowidget`, and see if that helps?

@drinfernoo this fixed the bug that i was having.. do you still want me to open a new issue?
The error that was being triggered is not there anymore and the content is loading on all of my widgets.. as it was

**Comment by rizreflects** [comment] 2021-09-10 12:55
Hey doc, I'd just like to run something by you if that's alright. If I go into cache.py and change 

DEFAULT_CACHE_TIME = 60 * 5 
to 
DEFAULT_CACHE_TIME = 60 * 1

Would this mean the cache will refresh once an hour from now on or isit much more complicated than that? Sorry if I'm coming across a bit stupid, I don't have any coding experience which is why I wanted to run it by you. I'm trying to reduce the amount of times I see the 'updating widgets' notification as that causes the problem I'm facing. If I could extend to once per hour instead of once every 10 minutes that would be perfect. Any help will be appreciated.

**Comment by drinfernoo** [comment] 2021-09-10 13:48
@rizreflects That would make the cache expire every minute 😅 

EDIT: Either way, that value has nothing to do with how quickly widgets refresh, only how soon the cache expires.

**Comment by drinfernoo** [comment] 2021-09-10 13:49
@antoniopetreski No, that's ok. Seems we've fixed it 😁

**Comment by djay** [comment] 2021-09-13 05:24
There is still a bug here from the except in the logs.
```
2021-09-07 20:40:22.283 T:6938    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/service.py", line 4, in <module>
                                                       _monitor = refresh.RefreshService()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/refresh.py", line 32, in __init__
                                                       self._update_widgets()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/refresh.py", line 90, in _update_widgets
                                                       queue = list(cache.next_cache_queue())
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/common/cache.py", line 70, in next_cache_queue
                                                       for path in iter_queue():
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/common/cache.py", line 48, in iter_queue
                                                       yield queue_data.get("path", "")
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--
```

the code for iter_queue is wrong.
```
def iter_queue():
    queued = filter(os.path.isfile, glob.glob(os.path.join(_addon_data, "*.queue")))
    # TODO: sort by path instead so load plugins at the same time
    for path in sorted(queued, key=os.path.getmtime):
        queue_data = utils.read_json(path)
        yield queue_data.get("path", "")
```

It's assuming the queue doesn't change mid way and have items deleted which isn't true.
What it should probably do is either reread the queue files each time or at least fix the problem if the file doesn't exist anymore.
If it's rereading it then potentially an update could keep getting extended by new widgets getting refreshed. not sure if thats desired or not
if the queue changes length as we go then ```queue = list(cache.next_cache_queue())``` that line would have to change and how we calculate the %.

**Comment by djay** [comment] 2021-09-13 05:49
I think between the two options having the queue get longer while its being processed is probably the better option. Otherwise the queue finishes and then appears to start again 15s later which would more annoying that % progress going backwards I think. and backwards progress you can at least associate with something you did recently.

**Comment by drinfernoo** [comment] 2022-08-16 16:04
@rizreflects Can you try the `3.7.0` release? This should be fixed now.

**Comment by rizreflects** [comment] 2022-08-16 17:33
I'm afraid I won't be able to test until the weekend. I'm currently working in another city and haven't brought my TV with me. I'll be sure to report back on the weekend.

**Comment by rizreflects** [comment] 2022-08-27 15:06
Sorry for the delayed response. The widgets have been working well now from my testing.

**Closed as completed** 2023-06-08 02:21 UTC
Labels: bug
