### ISSUE TITLE
[Bug] Kodi crashing

### ISSUE THREAD

**Issue by tatkodi** [drinfernoo/plugin.program.autowidget#114] opened 2021-09-20 16:13 UTC
AutoWidget has suddenly started crashing Kodi. The widgets and shortcuts work fine but when I open the AutoWidget add-on for configuration and then return to home, it often crashes Kodi. I thought removing nested shortcuts would fix the crashing but after that, the circumstances have changed although the crashing is persistent.

**DETAILS**
  - Kodi 19.1
  - Arctic Zephyr 2 Resurrection Mod
  - PC
  - Windows 10 x64

**LOG**
https://paste.kodi.tv/olupomenuj.kodi

**GROUP FILES**
https://www.dropbox.com/s/fvh3b0fdg9cc0dz/AW%20backup.zip?dl=1

**Comment by drinfernoo** [comment] 2021-09-20 16:15
Sounds to me like this is a duplicate of #111, then.

**Closed as completed by drinfernoo** 2021-09-20 16:15 UTC
Labels: bug
